sismo-core/sismo-hub

list-generators/generators/7_pooly-minters/index.ts, list-generators/generators/index.ts, list-generators/helpers/providers/big-query/big-query.ts, package.json, src/scripts/generate-list.ts
Add the getEvents function to the BigQuery data provider.
This function allows to get all events that match a given event ABI.
It uses custom typing template for easier developement with the query response.
Example:
```typescript
// Declare the event ABI
const NFTMintedEventABI =
"event NFTMinted(address indexed to, uint256 numberOfTokens, uint256 amount)";
// Declare your type
type NFTMintedType = {
to: string;
numberOfTokens: BigNumberish;
amount: BigNumberish;
};
// Call the getEvents function
// the result will be a NFTMintedType[] type. 
mintedEvents = await bigQueryProvider.getEvents<NFTMintedType>({
contractAddress,
eventABI: NFTMintedEventABI,
options: {
blockNumber: context.blockNumber,
},
});
// Use NFTMintedType[] type in the response:
const minterAddresses = …
```
=> add getEvents function to the BigQuery data provider

package.json, src/helpers/utils/store-data.ts
globstar `**` is not default and is disabled by default. Here, we use
eslint for globbing.
=> fix: run eslint recursivly

group-generators/helpers/providers/index.ts, group-generators/helpers/providers/rest-api/index.ts, group-generators/helpers/providers/rest-api/types.ts, package.json, yarn.lock
This PR adds a new provider that makes it easy to send requests to any rest API. 
- Create a new instance of the `RESTProvider` class
```
const restProvider = new dataProviders.RESTProvider();
```
- Define your API config & use the type `ApiConfig` from RestProvider types:
Example:
```
const ApiConfig: ApiConfig = { 
url: "https://lil-noun-api.fly.dev/ideas", 
method: 'GET',
data: {},
};
```
- Use the created instance to access the public method `fetchData()` and pass ApiConfig as a parameter
Like this:
```
const response = await restProvider.fetchData(ApiConfig);
```
=> add rest api provider

group-generators/generators/proof-of-attendance-main-events/index.ts
adding 82394 /* EthGlobal San Francisco POAP */ to eventIds
=> add: EthGlobal San Francisco POAP in proof of attendance main events

group-generators/generators/sismo-hub-contributors-github/index.ts, group-generators/generators/sismo-stargazers/index.ts, group-generators/generators/tuto-ens-contributors/index.ts, group-generators/helpers/data-providers/github/github.types.ts, group-generators/helpers/data-providers/github/index.ts
Formatting Github provider helper arguments to match other providers and adjusting corresponding group generators
=> fix: reformatting githubProvider arguments as other providers

.gitignore, src/topics/badge/badge.api.schema.ts, src/topics/badge/badge.api.test.ts, src/topics/badge/badge.api.ts
This PR update the badge api to : 
- output the `networks` field to the badge.
- `badges/:network/details/:collectionId` outputs a badge inside a single array `items` as the other endpoints
fix #801
=> Update for Sismo API

group-generators/generators/sismo-contributors-tier1-users/index.ts
Exclude Github Stargazer badges from Sismo contributors group to prevent farming
=> Fix: Exclude Stargazer badges from contributors

badges-metadata/base/hydra-s1/infrastructure/on-chain-roots-registry.ts
Polygon nodes miscalculate some gasLimit leading to registerRoot tx failure.
=> fix: register root tx for polygon chain

group-generators/generators/ethereum-balances/index.ts, group-generators/generators/index.ts
We add 3 groups based on whether they have 32, 64 and 128 ETH.
This can be used for gate-keeping wealthy people.
32, 64, 128 ETH are arbitrary values. Currently 32 ETH threshold doesn't generate too many holders: around 130k.
=> feat: groups based on ethereum balances

.github/actions/deploy/action.yml, .github/actions/generate-group-send-on-chain/action.yml, .github/actions/update-group-metadata/action.yml, .github/actions/update-groups-send-on-chain/action.yml, .github/workflows/check-new-groups-generation.yml, .github/workflows/deploy_dev.yml, .github/workflows/deploy_prod.yml, .github/workflows/deploy_staging.yml, .github/workflows/deploy_testnets.yml, .github/workflows/generate_group_prod.yml, .github/workflows/generate_group_staging.yml, .github/workflows/generate_group_testnets.yml, .github/workflows/update_group_metadata_prod.yml, .github/workflows/update_group_metadata_staging.yml, .github/workflows/update_group_metadata_testnets.yml, .github/workflows/update_groups_daily_prod.yml, .github/workflows/update_groups_daily_staging.yml, .github/workflows/update_groups_daily_testnets.yml, .github/workflows/update_groups_weekly_prod.yml, .github/workflows/update_groups_weekly_staging.yml, .github/workflows/update_groups_weekly_testnets.yml, group-generators/generators/guild-sismo-contributor/index.ts, group-generators/generators/guild-sismo-member/index.ts, group-generators/generators/index.ts, group-generators/helpers/data-providers/guild/index.ts, group-generators/helpers/data-providers/guild/interface-schema.json, group-generators/helpers/data-providers/guild/types.ts, group-generators/helpers/data-providers/index.ts
I've created a data provider for Guild.xyz according to the proposal #1429 .
I created a group generator for the Sismo Contributor Role in Sismo Guild. Works fine.
=> Data provider guild

group-generators/generators/ben-multiarg-group/index.ts, group-generators/generators/optimists/index.ts, group-generators/helpers/data-providers/atst/index.ts, group-generators/helpers/data-providers/atst/interface-schema.json, group-generators/helpers/data-providers/atst/queries.ts, group-generators/helpers/data-providers/atst/types.ts, group-generators/helpers/data-providers/index.ts
The previous implementation required that attestation matched specific key/value pairs.
This update allows to use the attestation values if these are numeric. Otherwise still counts as 1.
This allows for more control over the ATST data provider.
=> Update OP ATST to allow for value scoring

group-generators/generators/index.ts, group-generators/generators/zykloon-epoch-depositors/index.ts
This is the group generator for the depositors of the [`zykloon` vault contract](https://goerli.etherscan.io/address/0xe1581476e0a926c0ffc4e2e754c0bb82201378d7). The group is re-generated daily bi listening to the deposit events emitted in the latest 1024 blocks.
This group is part of the ZyKloon project, which is a ZKHack hackaton project.
=> feat: add zykloon-epoch-depositors group generator

group-generators/helpers/data-providers/eas/index.ts, group-generators/helpers/data-providers/eas/interface-schema.json, group-generators/helpers/data-providers/eas/types.ts, group-generators/helpers/data-providers/index.ts
This PR adds Ethereum Attestation Service (EAS) as a data provider.
https://easscan.org/
It allows you to search for attestation at different networks (currently supports mainnet, arbitrum and sepolia) by
- schema + attester
- schema + attester + key
- schema + attester + key + value
Some test data..
1.
network: sepolia
schema: 0x35d34c24b7c192050f4e3f2f2d4ccd65a3bc2e38b42eafa3e91973efbb1570fc
attester: 0x8289432ACD5EB0214B1C2526A5EDB480Aa06A9ab
View on EAS explorer https://sepolia.easscan.org/attestations/forSchema/0x35d34c24b7c192050f4e3f2f2d4ccd65a3bc2e38b42eafa3e91973efbb1570fc
2.
network: arbitrum
schema: 0xe093d91b9358e839e71dece1c23c00ce4d3e04fab8c2c9e393543165cdcdd2c0
attester: 0xa9cc4b8C03e88483A02ae9E1975857bc06bcFe90
key: Project_contribution_uuid
value: …
=> Add EAS data provider

group-generators/generators/dao-forum-users/index.ts, group-generators/generators/index.ts, group-generators/helpers/data-providers/discourse/index.ts, group-generators/helpers/data-providers/discourse/types.ts, group-generators/helpers/data-providers/index.ts
For EthGlobal Lisbon hackathon we want to fetch a list of Discourse users as a group generator.
Future work:
- Users should post signature instead of an address in their Discourse profile
- Data should be located in user fields instead of in the "name" field
The reasons we opted for these are time constraints, as discussed with @leosayous21 . We intend to develop further but project submission is in like 12h 🔥
=> Discourse data provider and group generator

src/topics/resolver/ens-resolver.ts, src/topics/resolver/github-resolver.ts, src/topics/resolver/lens-resolver.ts, src/topics/resolver/telegram-resolver.ts, src/topics/resolver/twitter-resolver.ts
ENS & Lens: are case sensitive and it only accept characters in a name, so now we put the account we want to resolve in the lower case at the very beginning of the resolve process.
Twitter, Telegram, GitHub: are also case sensitives but we can have usernames with upper or lower cases. In order to get the value associated with an account, we need to put names in lower case when filter the array of accounts (in case we out 0xmarTingbZ instead of 0xMartinGbz).
=> fix: resolvers (case sensibility issue)

badges-metadata/base/hydra/infrastructure/on-chain-roots-registry.ts
Increase gas limit for registering root on-chain. A lower limit was blocking for the arbitrum one chain
=> fix: increase gas limit for registering root on chain

package.json
=> fix: memory usage with correct node options when running

group-generators/generators/0xlegion-lens-follower/index.ts, group-generators/generators/ethereum-balances/index.ts, group-generators/generators/ethereum-most-transactions/index.ts, group-generators/generators/stani-lens-followers/index.ts, group-generators/helpers/data-providers/big-query/big-query.ts, group-generators/helpers/data-providers/index.ts, group-generators/helpers/data-providers/lens-bigquery/index.ts, group-generators/helpers/data-providers/lens-bigquery/interface-schema.json, group-generators/helpers/data-providers/lens-bigquery/queries.ts, group-generators/helpers/data-providers/lens-bigquery/types.ts
- Reproduce the Lens Provider using BigQuery
- Allow to fetch more data faster
- Add new functions:
- `getFollowers` (already here in Lens Provider)
- `getPublicationCollectors` (already here in Lens Provider)
- `getPublicationMirrorers` (already here in Lens Provider)
- `getPublicationCommenters`
- `getPublicationReactors`
- `getHashtagMentioners`
- Fix groups that got computation issues with the former Lens Provider
- Replace the Lens Provider by the BigQuery Lens provider in the Factory
=> feat: new Lens BigQuery provider

group-generators/generators/degenscore-beacon-holders/index.ts, group-generators/generators/galxe-eth-merge-day-participants/index.ts, group-generators/generators/guild-sismo-members/index.ts, group-generators/generators/index.ts, group-generators/helpers/data-providers/alchemy/index.ts, group-generators/helpers/data-providers/alchemy/interface-schema.json, group-generators/helpers/data-providers/alchemy/types.ts, group-generators/helpers/data-providers/ankr/index.ts, group-generators/helpers/data-providers/ankr/interface-schema.json, group-generators/helpers/data-providers/degenscore/index.ts, group-generators/helpers/data-providers/degenscore/types.ts, group-generators/helpers/data-providers/ens-subdomain/index.ts, group-generators/helpers/data-providers/galxe/index.ts, group-generators/helpers/data-providers/galxe/interface-schema.json, group-generators/helpers/data-providers/galxe/types.ts, group-generators/helpers/data-providers/guild/index.ts, group-generators/helpers/data-providers/guild/interface-schema.json, group-generators/helpers/data-providers/guild/types.ts, group-generators/helpers/data-providers/index.ts, group-generators/helpers/data-providers/otterspace/index.ts, group-generators/helpers/data-providers/otterspace/interface-schema.json, group-generators/helpers/data-providers/otterspace/types.ts, group-generators/helpers/data-providers/unlock/index.ts, group-generators/helpers/data-providers/unlock/interface-schema.json, group-generators/helpers/data-providers/unlock/types.ts
**TL;DR: this PR fix some issue we had on a few Data Provider functions, add something as value (balance, tokenId, creation date...) for the group (and not just a defaultValue), and also remove useless providers.**
Details:
- **Alchemy Provider:**
- feat: NFT Balance as value for getOwnersForCollection() function
- fix: getOwnersOfTokenIds function (wasn’t working anymore) + put tokenId as value (not possible to have the balance for this one)
- **Ankr provider:**
- feat: put balance as values for getTokenHolders (ERC-20 holders)  (not possible to have other things as value for NFT holders function)
- **DegenScore Provider:**
- feat: put the degen score as value instead of the minimal score specified
- Finally decided to remove it from factory because it’s just a fetch of onchain ERC-1155, …
=> feat: improve and fix data providers

package.json
=> fix: make-groups-available command in send-on-chain github action (heap

group-generators/generators/aave-holders/index.ts, group-generators/generators/apecoin-holders-by-chimeradefi/index.ts, group-generators/generators/clamato/index.ts, group-generators/generators/crypto-punks-holders/index.ts, group-generators/generators/first-1000-phonon-mainnet-holders/index.ts, group-generators/generators/hold-ape/index.ts, group-generators/generators/pal-holders/index.ts, group-generators/generators/pal-mainnet-holders/index.ts, group-generators/generators/phonon-mainnet-holders/index.ts, group-generators/generators/polygon-cake-holders/index.ts, group-generators/helpers/data-providers/token-provider/index.ts, group-generators/helpers/data-providers/token-provider/interface-schema.json
The `tokenDecimals` parameter was only used in the case there were a `minAmount` parameter set too (it was used to convert the minAmount into a non-wei number).
Because the token balance is now in wei, I think it makes more sense to have the minAmount also in wei. So we can also remove the `tokenDecimals` parameter
=> fix: tokenProvider ERC20 function

group-generators/helpers/data-providers/ankr/interface-schema.json, group-generators/helpers/data-providers/ankr/types.ts
Add `base` and `base_goerli` networks to the Ankr Provider. This addition benefits both developers and Factory users.
=> feat: add `base` and `base_goerli` networks for Ankr Provider

group-generators/generators/sismo-contributors-tier1-users/index.ts, group-generators/generators/sismo-contributors-tier2-impactful-contributors/index.ts
Badges are now deprecated, we change the group frequency of `sismo-contributors-tier1` and `sismo-contributors-tier2` to `Once` to avoid querying Sismo Subgraphs.
=> chore: update group frequency sismo-contibutors ter1/tier2

package.json
Daily update workflows are failing due to Node running out of memory. I am increasing the memory to 8GB.
=> chore: increase node `max-old-space-size` for `generate-all-groups` command

.github/workflows/generate_group_prod.yml, .github/workflows/generate_groups_send_on_chain_prod.yml, .github/workflows/remove_groups_prod.yml, .github/workflows/update_groups_daily_prod.yml, .github/workflows/update_groups_weekly_prod.yml
Scroll Alpha Testnet has been deprecated by the Scroll team https://guide.scroll.io/user-guide/bridge/deposit-from-goerli-to-scroll. Therefore, we will not update any roots on the Scroll Alpha Testnet anymore.
=> chore: deprecate Scroll Alpha Testnet

.github/actions/generate-groups/action.yml, .github/actions/update-groups-send-on-chain/action.yml
Update workflows were failing due to using `yarn cli <command>` instead of `yarn <command>`. By using the command directly referenced in `package.json` we are specifying the extra memory allocation properly for the workflow.
=> fix: remove `cli` command in workflows to increase the `max-old-space-size` used by node

README.md
The old twitter badge is replaced by new x badge.
=> X Badge Update in README.md
