- group-generators/generators/index.ts
- group-generators/generators/masquerade-lens-followers/index.ts
- group-generators/generators/pooly-lawyer-minters/index.ts
- group-generators/generators/sismo-and-masquerade-lens-followers/index.ts
- group-generators/generators/sismo-lens-followers/index.ts
- group-generators/generators/sismo-masquerade-lens-followers/index.ts
- group-generators/helpers/data-operators/Intersection.ts
- group-generators/helpers/data-operators/index.ts
- group-generators/helpers/providers/index.ts
- group-generators/helpers/providers/lens/index.ts
- group-generators/helpers/providers/lens/queries.ts
- group-generators/helpers/providers/lens/types.ts
- src/group-generator/group-generator.ts
- src/helpers/utils/disk.ts
- src/helpers/utils/generation-context.ts
Create the new group generator: sismo masquerade followers
The lens data providers has been created to regroups all profiles queries and followers queries.
> Add lens data provider and sismo masquerade followers groups

- group-generators/generators/ethereum-event-attenders/index.ts
- group-generators/generators/index.ts
- group-generators/generators/sismo-diggers/index.ts
- group-generators/helpers/providers/index.ts
- group-generators/helpers/providers/poap/cross-chain/provider.ts
- group-generators/helpers/providers/poap/cross-chain/types.ts
- group-generators/helpers/providers/poap/index.ts
- group-generators/helpers/providers/poap/provider.ts
- group-generators/helpers/providers/poap/types.ts
Supports Ethers Mainnet and xDai
> feat: add Poap Cross Chain Subgraph Provider

- group-generators/helpers/providers/poap/cross-chain/provider.ts
* feat: transform BigNumbers into numbers in resulting generation
> fix: poap multi chain provider

- attestations-collections/hydra-s1-simple-sandbox/index.ts
- attestations-collections/hydra-s1-simple/index.ts
- attestations-collections/index.ts
- flows/sandbox-flows.ts
Fix to make the tutorial working, `local-group` is mandatory to be generated by the dev, sandbox environment added to make the PR
> fix: add sandbox environment

- attestations-collections/index.ts
add rinkeby attester for `compute-attester` command
> fix: add rinkeby attester

- flows/live.ts
- flows/local.ts
- flows/playground.ts
- flows/staging.ts
This reverts commit a72329e8adb684ba6aee671b9992bfeb8bd02b22.
> revert: titles in flow

- group-generators/generators/ben-friends/index.ts
Change ben-friends group generation frequency from **Daily** to **Once**
> fix: change ben-friends group generation frequency

- group-generators/generators/ethereum-adopter/index.ts
- group-generators/generators/lyca/index.ts
> fix: generation frequency to Once for groups using epu

- group-generators/generators/sismo-contributors-tier1-users/index.ts
- group-generators/generators/sismo-contributors-tier2-impactful-contributors/index.ts
[SIP-12] This update is based on the following approved [Snapshot Proposal](https://snapshot.org/#/sismo.eth/proposal/0x6b0c32f57d7f4943811ccdcf00246e3cb5a4e3faeffd0f067ce25e8ef8b23ffa)
> SIP-12: Update Sismo Contributor ZK Badge eligibility requirements

- .github/actions/generate-group-send-on-chain/action.yml
- .github/actions/update-groups-send-on-chain/action.yml
- .github/workflows/check-new-groups-generation.yml
- .github/workflows/generate_group_prod.yml
- .github/workflows/generate_group_staging.yml
- .github/workflows/generate_group_testnets.yml
- .github/workflows/update_groups_daily_prod.yml
- .github/workflows/update_groups_daily_staging.yml
- .github/workflows/update_groups_daily_testnets.yml
- .github/workflows/update_groups_weekly_prod.yml
- .github/workflows/update_groups_weekly_staging.yml
- .github/workflows/update_groups_weekly_testnets.yml
- group-generators/generators/index.ts
- group-generators/generators/web3-social/index.ts
- group-generators/helpers/data-providers/farcaster/index.ts
- group-generators/helpers/data-providers/farcaster/types.ts
- group-generators/helpers/data-providers/index.ts
- group-generators/helpers/data-providers/lens/index.ts
- group-generators/helpers/data-providers/rest-api/index.ts
- group-generators/helpers/data-providers/utils/utils.ts
- v1 of web3-social group:
- all Lens users (NFT Profile holders)
- all Farcaster users (fids)
- Creation of a retry function => take in consideration all request errors (not only 429 errors)
> Web3 social group

- badges-metadata/main/factory/hydra-s1-accountbound-factory-badges.ts
Stopping "Pinata" ZK Badge as there is no remaining credit https://factory.sismo.io/explorer/ea34c6cf-0530-4049-9a2a-b14dedadc3f9
> feat: stop pinata badge mints

- group-generators/generators/zkpay-quest/index.ts
> Typo in URL

- group-generators/generators/zohal-KYC/index.ts
Changed API URL to get verified users
> Zohal new API update

- src/topics/group-generator/group-generator.ts
Add logs of group data links at the end of group generation
> Add links to group data

- group-generators/generators/index.ts
- group-generators/generators/tutorial-sismo-early-interactors/index.ts
This is a example PR for the tutorial [Create a Group](https://docs.sismo.io/sismo-docs/tutorials/create-your-group-developers).
This PR shows the different files that you need to change in order to deploy your Group Generator on the [Sismo Hub](https://github.com/sismo-core/sismo-hub) and the [Sismo Factory](https://factory.sismo.io/create-badge).
> feat: add tutorial-sismo-early-interactors group generator

- group-generators/generators/talentlayer/index.ts
- group-generators/helpers/data-providers/index.ts
- group-generators/helpers/data-providers/talentlayer/index.ts
- group-generators/helpers/data-providers/talentlayer/interface-schema.json
- group-generators/helpers/data-providers/talentlayer/queries.ts
- group-generators/helpers/data-providers/talentlayer/types.ts
* add talentlayer data provider
* fix: added count structure with not optimal query -> count query should be provided on The Graph for increased performance
* renaming functions
* fix: add count function to dataprovider index
* update data structure
* remove argument
* update response format
* Add new users group for talentLayer
---------
> feat: add talentlayer data provider (#1523)

- README.md
- src/topics/group-generator/group-generator.ts
Some minor updates on the group generator. 
Is it correct the docs @ docs.sismo.io are not on Github? 
If so, happy to propose some changes to that as well
> Update group generator docs

- group-generators/generators/index.ts
- group-generators/generators/poap-polygon-group/index.ts
Added group for addresses eligable for badges as proof-of-attendence for ETHDenver RIVER arthouse
> feat: add poap group

- group-generators/generators/pvnz/index.ts
Want to add my friends to be able to mint my Sismo badge :)
> Add new eligible wallet

- group-generators/generators/poap-polygon-group/index.ts
> participant update 27/3/23

- group-generators/generators/poap-polygon-group/index.ts
> group update 30.03.2023

- group-generators/generators/fantom-alpha-round-donaters/index.ts
I got a lot of questions about whether this is an official badge. Decided to be clear.
> Update badge description

- group-generators/generators/example-galxepassport/index.ts
- group-generators/generators/index.ts
As per issue issue [1450 here](https://github.com/sismo-core/sismo-hub/issues/1450)
> feat: Galxe passport group

- group-generators/helpers/data-providers/talentlayer/index.ts
Update the url provider after mainnet launch
> Update the talentlayer url provider

- group-generators/helpers/data-providers/talentlayer/index.ts
- group-generators/helpers/data-providers/talentlayer/interface-schema.json
- group-generators/helpers/data-providers/talentlayer/queries.ts
https://trello.com/c/3lks5V1J/280-zkpow-integration
> Improvements

- group-generators/generators/delovoy-dao-christmas/index.ts
Add one more eligible address: gosleep01.eth
> Add eligible address

- group-generators/generators/index.ts
- group-generators/generators/philand-quest-uniswap-v3-swaps/index.ts
Resolves https://github.com/sismo-core/sismo-hub/issues/1748
> Generator for Uniswap Mainnet users by swap count

- group-generators/generators/index.ts
- group-generators/generators/kycdao-valid-members/index.ts
as per https://github.com/sismo-core/sismo-hub/issues/1448
Group currently works with ANKR's public API w/o apikey - takes about 2 minutes. If the group grows in size, then we should add our API key to increase the speed
> feat: kycdao valid group members

- group-generators/generators/example-alchemy/index.ts
- group-generators/generators/example-layer3/index.ts
- group-generators/generators/index.ts
- group-generators/generators/parallel-identity-holders-accredited/index.ts
- group-generators/generators/parallel-identity-holders-sanctions-safe/index.ts
- group-generators/generators/parallel-identity-holders/index.ts
- group-generators/helpers/data-providers/alchemy/index.ts
- group-generators/helpers/data-providers/alchemy/interface-schema.json
- group-generators/helpers/data-providers/alchemy/types.ts
- group-generators/helpers/data-providers/index.ts
Replacing this PR - I had issues with Git.
https://github.com/sismo-core/sismo-hub/pull/1845
This is for Issue https://github.com/sismo-core/sismo-hub/issues/1446
> feat: group parallel identity

- group-generators/generators/the-merge-contributor/index.ts
> Add contributors

- group-generators/generators/aavechan-delegators/index.ts
> threshold change for demo app

- src/topics/group-generator/group-generator.test.ts
- src/topics/resolver/github-resolver.ts
- src/topics/resolver/global-resolver.ts
- src/topics/resolver/memory-resolver.ts
- src/topics/resolver/telegram-resolver.ts
- src/topics/resolver/twitter-resolver.ts
- src/topics/resolver/utils.ts
> fix: web2 resolvers for web2 accounts with identifiers or not in the

- .vscode/settings.json
- docs/github-provider.md
- docs/poap-provider.md
- docs/token-provider.md
- group-generators/helpers/data-providers/github/index.ts
Add documentations for the following Data Providers:
- GitHub
- Token
- POAP
> feat: add data provider docs

- group-generators/generators/gitcoin-passport-holders/index.ts
Gitcoin Passport team updated their public API endpoint for Passport holders as well as the data format.
> chore: update `gitcoin-passport-holders` data endpoint
